on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          # this assumes that you have created a personal access token
          # (PAT) and configured it as a GitHub action secret named
          # `MY_RELEASE_PLEASE_TOKEN` (this secret name is not important).
          token: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}
          # this is a built-in strategy in release-please, see "Action Inputs"
          # for more options
          release-type: simple

    # Customizing the release-please action
    # If you want to customize the release-please action, you can do so by
    # specifying a custom configuration file. This is useful if you want to
    # change the default behavior of the action, such as the release type,
    # the commit message format, or the changelog format. Comment the above and uncomment the code below.
    # Make sure to read the docs for the release-please action to understand how to create a manifest file.
    # steps:
    # - uses: googleapis/release-please-action@v4
    #     with:
    #     # this assumes that you have created a personal access token
    #     # (PAT) and configured it as a GitHub action secret named
    #     # `MY_RELEASE_PLEASE_TOKEN` (this secret name is not important).
    #     token: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}
    #     # optional. customize path to release-please-config.json
    #     config-file: release-please-config.json
    #     # optional. customize path to .release-please-manifest.json
    #     manifest-file: .release-please-manifest.json