services:
  postgres:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: authservice

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  # Work in progress :(
  # Could be postgres DSN ENV variable, and/or a race condition between postgres init, and auth-service init.
  # auth-service:
  #   environment:
  #     - ENV=${ENV}
  #     - POSTGRES_DSN='host=postgres user=postgres password=password dbname=authservice port=5432 sslmode=disable TimeZone=America/Los_Angeles'
  #   build:
  #     context: .
  #     tags:
  #       - authservice:latest
  #   ports:
  #     - "9090:9090"
  #   depends_on:
  #     - postgres
